version: '3'
services: 
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'boiler'
      MYSQL_USER: 'boiler'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mydb:/var/lib/mysql
  rdcaches:
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:5.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ADVERTISED: 0.0.0.0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0  
  nemo:
    image: meongbego/review1
    restart: always
    ports:
      - 3000:3000
    environment:
      - GIN_MODE=release
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3000
      - SERVER_TIMEZONE=Asia/Jakarta
      - DB_MYSQL_USERNAME=bigevent
      - DB_MYSQL_PASSWORD=root
      - DB_MYSQL_HOST=database
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_DATABASE=bigevent
      - REDIS_HOST=rdcaches
      - REDIS_PORT=6379
    command: ./main -e production
    tty: true
    depends_on:
      - database
      - rdcaches